<?php

namespace App\Http\Requests\Auth;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\App;

class LoginRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            "email" => 'required|email|string',
            "password" => 'required|min:3|max:20|string',
            'remember' => 'required|boolean'
        ];
    }

    public function messages()
    {
        if (App::getLocale() == 'en') {
            return parent::messages(); // TODO: Change the autogenerated stub
        }
        if (App::getLocale() == 'ru') {
            return [
                'email.required' => 'Поле Email обязательно',
                'email.email' => 'Поле Email должно быть в следующем формате some@mail.ru',
                'password.required' => 'Поле Пароль обязательно',
                'password.min' => 'Минимальная длина 3',
                'password.max' => 'Максимальная длина 20',
            ];
        }
    }


}
